# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target ‘FBook’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBook
  pod 'Alamofire', '~> 4.4'
  pod 'ObjectMapper', '~> 2.2'
  pod 'Kingfisher', '~> 3.0'	
  pod 'PKHUD', '~> 4.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'SwiftyStarRatingView'
end
